### ISSUE TITLE
USER Allow attendee to appear Anonymous in attendee lists for events

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#103]
To protect identities of people, we should allow them to appear anonymous in attendee lists of events if they choose.

**Comment by MervinHernandez** [comment]
I'm suggesting a  check box in the RSVP window, to allow someone to select "List me as annonymous"

![Image](https://user-images.githubusercontent.com/8400371/192873285-015310bd-93d3-4804-be4d-e56f5c6ada78.png)

**Comment by mauteri** [comment]
Adding this to MVP. One other feature is that higher roles can see all people whether they are anonymous or not. I'll probably start this as `administrator` but eventually create a capability. Need to think about that more and chat with folks.
