### ISSUE TITLE
LAUNCH v1

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#104]
# PREPARE GatherPress v1 items for launch

## 1. MOVE Site to Faster Hosting
- [ ] ENSURE We have the latest GP plugin installed

## 2. FINALIZE Documentation (v1)

* Practical use quickstart
    1. Setup a venue
    2. Setup an event
    3. Setup registration form
    4. Setup Email notification upon RSVP

## 3. CONFIGURE SendGrid
> See Slack from Cam (May 4 2022) for API )

- [x] CREATE API Key 
- [x] AUTHENTICATE Sender (DNS CNAME Records on `gatherpress.org` domain)
- [x] INSTALL Post SMTP Plugin on WP
- [x] CONFIGUE Post SMTP Plugin on WP (API Key + Outbound Envelope Information)

## 5. Announce Launch
- [ ] SEND Notification out to list of audience
- [ ] Courtney - PITCH Podcast Appearances for GatherPress

## 6. TRACK Post-Launch
- [ ] CREATE Google Alert for "GatherPress" mentions

**Comment by MervinHernandez** [comment]
# ✅ Configured SendGrid
Now, must confirm that all the things use `site@noreply.gatherpress.org` as the "from" envelope address. @mauteri

**Comment by meaganhanes** [comment]
Happy to help with styling the site, provided I get access to doing so!

**Comment by mauteri** [comment]
@meaganhanes Sorry, just seeing your comment now (4 months late). If you're still interested in styling you can definitely help us with styling gatherpress.org. We also have very minor styling we do in the plugin, so could use some of your insight there too if you like. Thanks!

**Comment by mauteri** [comment]
@MervinHernandez just checking on this ticket if it's still relevant or not. We've done a few things listed already since this was last updated.

**Comment by carstingaxion** [comment]
@mauteri! @MervinHernandez: Are there valid reasons to keep this issue open? It seems heavily outdated to me.

**Comment by mauteri** [comment]
Yes, this was a very old ticket. Closing.
