### ISSUE TITLE
SSO (Add-On Plugin)

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#105]
# Concepting

## WordPress.org ??

**Comment by MervinHernandez** [comment]
This is at a stand-still until #Community team further dialogues with us, and grants us access.

**Comment by MervinHernandez** [comment]
Pinged Dan to check on the status / availability of this.

**Comment by mauteri** [comment]
@MervinHernandez Closing this ticket. This is out of scope for the GatherPress team. If the meta team thinks we need this we can work with them on it, but this isn't something the GatherPress team should be working on as part of this project and shouldn't be on our board.
