### ISSUE TITLE
EMAIL Pre-Post Event

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#117]
Email attendees before the event to remind them of their upcoming attendance reservation 
Email attendees after the event, and include the link to watch the replay if they did not attend in person.

**Comment by mauteri** [comment]
@MervinHernandez I think for MVP we need
* Announce with optional message
* Update with optional message

Announce prompt will happen after an event is published. Update prompt will happen after a published event is updated (content changed, publishing status changed). In addition, a manual update can happen whenever, but WordPress will trigger a prompt for Announce or when content/status changes.
