### ISSUE TITLE
Review 0.4.1 on GatherPress.org

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#131]
Report any bugs and possible improvements.

**Comment by MervinHernandez** [comment]
# Q: Should the `organizer` metadata be displaying on the front end?


![Image](https://user-images.githubusercontent.com/8400371/187086427-4d29b759-1aa6-4d8d-94bb-b03291ab37d4.png)

**Comment by MervinHernandez** [comment]
# ✅ Topic Saved / ❌ Not displayed in front-end

* Topic added (via gutenberg post `Topic` meta = did save successfully (visible in Topics taxo upon save)
* This piece of meta did not show up in the front end

**Comment by MervinHernandez** [comment]
@mauteri see comments

**Comment by mauteri** [comment]
* What do you mean by Organizer metadata? What are you seeing that should/shouldn't be there?
* There's no frontend display of Topics. We can discuss and add that in a future ticket once deciding how it should be displayed and where.

**Comment by MervinHernandez** [comment]
@mauteri what I mean is, at the moment, only the event creator (writer) is displayed. 
Should we not also see "Organizer" and others, if those are populated?

**Comment by mauteri** [comment]
Yeah, this was missed. We need a ticket for creating a block that let's you select/display organizers that are set under Leadership in settings. Mind putting in that ticket and prioritizing it? Thx!
