### ISSUE TITLE
BUG Dates on Event Details

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#150]
The date in the date-picker, is not reflected in the event details displayed, even after saving. 

![Image](https://user-images.githubusercontent.com/8400371/188478452-b1ece94b-e701-4b13-8fe3-2b7690df201e.png)

**Comment by mauteri** [comment]
You're going to have to walk me through this one. The time updates on blur. So when you change it, as soon as you leave the field, it updates. It functions exactly as changing publish date. At least for me. If you have a workflow that is different from mine, I'd like to see it.

**Comment by MervinHernandez** [comment]
1. I select a date-time for the event
2. I save the event 
3. This "Start" field, does not reflect the date I selected.

**Comment by pbrocks** [comment]
more discussion in [Slack](https://gatherpress.slack.com/archives/C010M3FV65V/p1665072935496199)

**Comment by pbrocks** [comment]
![image](https://user-images.githubusercontent.com/5721313/209586557-709ebad4-c9a6-4e24-88a5-63c5b98d835c.png)

**Comment by pbrocks** [comment]
@MervinHernandez This should be fixed/closed
