### ISSUE TITLE
BUG Unable to leave `Venue` Blank for New Event

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#151]
Attempted creating new event, without a Venue set = ❌ unable to leave this "blank", it is defaulting to the one (first created) venue.

**Comment by mauteri** [comment]
Oh, yeah, I see. So two things need to happen here:
* Have no venue as an option and not disabled (currently, it's disabled).
* Have something render in the block when nothing is selected, so it is easy to find/select the block.

**Comment by pbrocks** [comment]
@mauteri was this fixed? I haven't noticed this issue on latest. Like maybe fixed with [this](https://github.com/GatherPress/gatherpress/blob/main/templates/blocks/venue-information.php#L20)?

**Comment by carstingaxion** [comment]
Tested this again, while working on https://github.com/GatherPress/gatherpress/issues/629 and can not reproduce the issue.

Within an event one can leave the _venue_ blank & save. After a reload of the editor, no venue is set. Everything is fine & like expected.

**Comment by mauteri** [comment]
Going to close this one. Thanks for testing @carstingaxion!
