### ISSUE TITLE
ADD Venue to Events List Block

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#155]
Events List Block needs to display venue name that is linked to Venue page.

**Comment by MervinHernandez** [comment]
PLUS - debug why this content (venue) does not render in the front end 

![Image](https://user-images.githubusercontent.com/8400371/192869406-090570ff-4b95-46bc-a610-d28f9992d0cb.png)

**Comment by jmarx** [comment]
@MervinHernandez You can assign this to me.

**Comment by jmarx** [comment]
@MervinHernandez I believe the issue in your screenshot(The venue not displaying on the event template).
Is solved by this code which was merged last week:
https://github.com/GatherPress/gatherpress/pull/161/files#diff-2289f56eecb10faaa9f12edf27aa910fe9e69ab4da1bee92de6b013e74035402R147-R153
From this PR:
https://github.com/GatherPress/gatherpress/pull/161/files#diff-2289f56eecb10faaa9f12edf27aa910fe9e69ab4da1bee92de6b013e74035402R147-R153
It was referencing a very old issue:
https://github.com/GatherPress/gatherpress/issues/76

Upon creation of a new event, you should see a set of blocks available by default on the editor screen.
![Screen Shot 2022-10-10 at 2 07 30 PM](https://user-images.githubusercontent.com/223919/194928417-8e0448ba-d4a7-4e96-a471-5970153e3d01.png)

Once you add details and save/publish the event, you should see all these details(Including the venue) on the front end of the single event template.

![Screen Shot 2022-10-10 at 2 13 02 PM](https://user-images.githubusercontent.com/223919/194928856-8a5451a3-6dc7-43ec-9211-898cf8b125a5.png)

Can you do me a favor and make sure that I am understanding the issue correctly? And please try and create an event and make sure you see the venue as we would expect? If not, let's schedule a zoom session so I can see what you are seeing.

Then @mauteri this Pr should be ready to be reviewed assuming @MervinHernandez 's concerns are satisfied.
https://github.com/GatherPress/gatherpress/pull/166

**Comment by MervinHernandez** [comment]
Hi @jmarx . After updating WP Nashville to the latest 0.1, this issu persists.
Populated data for event venue, is not displayed in the front-end to visitors, despite being added via block in the FSE editor.


![Image](https://user-images.githubusercontent.com/8400371/195996683-0e34b9cc-01e1-4b1f-8de7-6e05c8ba1658.png)

**Comment by pbrocks** [comment]
@MervinHernandez What you are describing is the expected behavior. On the backend, `Add Venue Information` shows in case you want to add some. On the frontend if you don't have any Venue selected, nothing shows. Are you asking that the empty Venue info shows up on the frontend, too?

If not, I'd say we close this.

**Comment by MervinHernandez** [comment]
This event shown on the screenshot, has a venue associated with it. It is not rendering on the front end, if the layout is set by the custom Guten template.

**Comment by pbrocks** [comment]
> This event shown on the screenshot, has a venue associated with it. It is not rendering on the front end, if the layout is set by the custom Guten template.

This isnt true. 

`No Venue Selected` means that "no venue IS selected"

![image](https://user-images.githubusercontent.com/5721313/209585693-edaa1202-be7f-442a-9e76-a632d5e5ec4a.png)
