### ISSUE TITLE
BLOCK Event list block not displaying in the front end

### ISSUE THREAD

**Issue by jmarx** [GatherPress/gatherpress#169]
@mauteri 

@pbrocks and I noticed that the event list block displays on the back end:
![Screen Shot 2022-10-09 at 11 02 57 AM](https://user-images.githubusercontent.com/223919/194764204-06027693-b9af-4abd-9177-c5f674cd0d16.png)

But not on the front end:
![Screen Shot 2022-10-09 at 11 05 57 AM](https://user-images.githubusercontent.com/223919/194764315-73913787-6b17-404e-abe0-7d9fe5809ab7.png)

**Comment by pbrocks** [comment]
@jmarx @MervinHernandez close?
