### ISSUE TITLE
Disable Attendance Selector if not logged in or event has past.

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#18]

**Comment by mauteri** [comment]
@MervinHernandez I started this one out as just a simple check if not logged in or if event past. If either is true we just don't render the attendance block. We can make this fancier at some point (eg, disabled selected), but not necessary at this point.

**Comment by MervinHernandez** [comment]
✅ Confirming expected behavior: if not logged in = does not render.
✅ Confirming expected behavior: if event has passed = does not render.
