### ISSUE TITLE
EDIT Text - Attending Count

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#196]
# EDIT Attendee Count (Front End) 
- [ ] change the “number attending”  to “number attending including yourself”

---

#qalaura

**Comment by mauteri** [comment]
I don't think we need this one. I thought this one was a bit confusing. It's pretty explicit about saying guests. It also follows meetup UI for this.

**Comment by mauteri** [comment]
@MervinHernandez closing this one. Guests feature was put on the back burner and removed from the MVP. We'll be scoping out the guests feature when we're ready to implement it.
