### ISSUE TITLE
BLOCK Limit Event and Venue blocks to events and venues

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#207]
Some blocks should be limited where they are available.

Event only blocks: `add-to-calendar`, `attendance-list`, `attendance-selector`, `event-date`, `venue`
Venue only blocks: `venue-information`
Everywhere: `events-list`

**Comment by carstingaxion** [comment]
I'd like to re-open this issue, please.

The changes made here, should be finer adjusted. I agree that it is not necessary to have all blocks available everywhere, but the actual approach is slightly too restrict.

The Un-Registration of blocks based on the currently edited post completely seems to ignore the existence of the `core/query` block and its possibilities. The same applies to all query-block-variations.

I think, but I'm not sure, the jetpack plugin had some nice way of unsetting a blocks `scope` property, so it became invisible under given circumstances.

**Comment by mauteri** [comment]
@carstingaxion this was already un-done [here](https://github.com/GatherPress/gatherpress/issues/526) as we realized we needed blocks available for FSE templates, widget areas, etc and what we had was too restrictive.

**Comment by carstingaxion** [comment]
> @carstingaxion this was already un-done [here](https://github.com/GatherPress/gatherpress/issues/526) as we realized we needed blocks available for FSE templates, widget areas, etc and what we had was too restrictive.

Oops. 

Your PR description sounds much like what I wanted to say with my comment over here.👍 Great!

I'll take a closer look, what I've missed.
Thanks @mauteri
