### ISSUE TITLE
BLOCK Event List block add filter by Venue

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#236]

**Comment by jmarx** [comment]
Hey @mauteri I understand the concept.But I wanted to get a little more specific.
You are looking to replicate this functionality?
![Screenshot 2023-07-16 at 9 33 22 AM](https://github.com/GatherPress/gatherpress/assets/223919/724d3b36-5064-4d13-a97e-47093c0efc69)
And you'll want to a dropdown here with a list of venues?

Also, would you want this filter to also appear in the front end for end users? Or just in the block panel here?

**Comment by mauteri** [comment]
@jmarx See where it says `TOPICS`? Add `VENUES` above that and follow same sort of logic.
