### ISSUE TITLE
BLOCK Add Venue selector to Venue block

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#238]

**Comment by pbrocks** [comment]
@mauteri I don't understand what you mean here. I've actually been thinking that the Venue block should be renamed to Event Venue to avoid ambiguity of what the Venue block is for.

**Comment by pbrocks** [comment]
Add Venue selector to Event Venue block's sidebar controls.

**Comment by mauteri** [comment]
@pbrocks finished this one, so going to move to done.
