### ISSUE TITLE
Remove support for PHP 7.3

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#276]
Current breakdown of versions of PHP running WordPress

PHP 5.6: 9.1%
PHP 7.0: 4.2%
PHP 7.1: 2.8%
PHP 7.2: 2.1%
PHP 7.3: 1.5%
PHP 7.4: 55.8%
PHP 8.0: 28.2%
PHP 8.1: 9.3%
PHP 8.2: 6.7%
Other: 0.1%

Only 1.5% are running PHP 7.3, so it doesn't make sense to support this version. We should change minimum requirement from 7.3 to 7.4.

Updates also include updating GH Actions as well as checking for minimal version before activating the plugin.

**Comment by mauteri** [comment]
[Caleb](https://github.com/bluecollarcoders) said he'd like to do this one

**Comment by jeffpaul** [comment]
@mauteri this looks to be done in the codebase and the issue can likely be closed (though I didn't bother to track down the specific PR or commit to use as a reference when closing)

**Comment by jeffpaul** [comment]
Also noting that https://github.com/10up/wp-compat-validation-tool might be helpful in situations where GatherPress should gracefully exit on activation when system requirements aren't met (e.g. PHP/WP versions).

**Comment by mauteri** [comment]
@jeffpaul that would be cool to look into, thx! currently i have a graceful exit for PHP baked into the plugin, but if there's a tool that will do both PHP and WP that would be better.

**Comment by mauteri** [comment]
@jeffpaul I bookmarketed and starred compat tool to look at and implement soon. thx!
