### ISSUE TITLE
Add PHP 8.1 and 8.2 to PHP Version Matrix in GH Actions

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#278]
WordPress supports PHP 8.1 and 8.2 so we should add it to our PHP version matrix

**Comment by jeffpaul** [comment]
@mauteri this looks to be done within the phpunit tests, so you can likely close out this issue (though I didn't bother to trace down the PR or commit where this was updated for reference)

https://github.com/GatherPress/gatherpress/blob/ce762ba6a187d9f0fab53ef7daea1dbece8e9e2d/.github/workflows/phpunit-tests.yml#L15
