### ISSUE TITLE
Suggesting Rewording

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#38]
https://github.com/GatherPress/gatherpress/blob/0a1891bb1ed2784b5c6748bc871c232e88772621/core/classes/class-settings.php#L304

Recommending we rename this to something more descript - "Menu Structure" I understand to be related to nav menu's or other structural item. In essence, not to the "Display Attendee Count by Reservation".

**Comment by mauteri** [comment]
@MervinHernandez I'm going to remove this the Language section, so I think this is going to be closed.

We can leave language as it is. If people don't like it they can add a language file to change it or someone can write a plugin to change this language if they feel like it at some point. I think this feature was misguided on my part.

**Comment by mauteri** [comment]
Going to close this one issue #67 will remove this section entirely.
