### ISSUE TITLE
Update documentation in cloning about changing plugin name

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#382]
- [ ] ADD Recommended implementation of "Login" or "register" // as this is default behavior of WP, and thus, this plugin

**Comment by mauteri** [comment]
@pbrocks was this ticket put in because the development on the plugin has issues when you name it anything other than `gatherpress`? Is that what this ticket means? (not sure how that checkbox is related either)

**Comment by carstingaxion** [comment]
@mauteri After that long time with no clarification, I suggest closing this issue.

**Comment by mauteri** [comment]
Closing.
