### ISSUE TITLE
Add and complete readme.txt

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#406]
We only need a README.md (not a readme.txt). Let's bring these together into just the README.md and remove the readme.txt.

More info here: https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/

Example of how to format here: https://github.com/johnbillion/user-switching/blob/develop/readme.md

**Comment by mauteri** [comment]
@patriciabt I think this is all done, right?

**Comment by mauteri** [comment]
Ok great, if you can handle first bullet point that would be awesome. I'll handle second bullet point. Thx!

**Comment by carstingaxion** [comment]
We should not forget about, what @jeffpaul noted in the closed PR:

>Still needed is:
>
>- [ ] Update the description of the GatherPress repo from the No description, website, or topics provided. placeholder to GatherPress, powering our community's event management needs. or something like that.
>- [ ] Generate a [plugin header image](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-headers) and add to the repo (.wordpress-org folder so they'll get deployed to WP.org on the next release published there)
>- [ ] Generate some [plugin screenshots](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#screenshots) and add those to the repo and reference in the readme files

and like @mauteri and me concluded in the GatherPress slack channel, we should also:

- [ ] [Use only a README.md file](https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/), [which is also valid for wp.org](https://meta.trac.wordpress.org/ticket/403) since 2015

**Comment by jeffpaul** [comment]
The following one is done:
> - Generate a [plugin header image](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-headers) and add to the repo (.wordpress-org folder so they'll get deployed to WP.org on the next release published there)

See: https://github.com/GatherPress/gatherpress/blob/main/.wordpress-org/banner-1544x500.jpg && https://github.com/GatherPress/gatherpress/blob/main/.wordpress-org/icon-256x256.jpg

**Comment by carstingaxion** [comment]
I'd like to start working on this one.

**Comment by patriciabt** [comment]
@carstingaxion 
We can do it together.
[This post by John Blackbourn](https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/#more-1228) is what was mentioned during the meeting 

- [ ] We remove the readme.txt and keep only the readme.md
- [ ] I see with @mauteri for the team member list update
- [ ] You gather all technical/dev information to be added/modified/removed
- [ ] I do the same for all non technical information

If that's OK for you?

**Comment by carstingaxion** [comment]
> @patriciabt If that's OK for you?

Absolutely.

*But, now that you respond, I remember that you wanted to deal with that README. I'm sorry, I didn't wanted to step on your foot, be earlier or start mansplaining in any way.*

**Comment by patriciabt** [comment]
@carstingaxion 
That's so kind to mention that, but absolutely no worries at all, on the contrary!
Especially that I have no idea about all the things to mention :) related to that: [Undocumented use of a 3rd Party or external service #610](https://github.com/GatherPress/gatherpress/issues/610)

Thanks a lot!

**Comment by carstingaxion** [comment]
Great @patriciabt , let's start!

**Comment by carstingaxion** [comment]
>related to that: https://github.com/GatherPress/gatherpress/issues/610

**I'm unsure too**, because I can't remember any plugin in the repository linking to TOS or privacy policies of 3rd-parties.

Let's go on with what @jeffpaul suggested:

>= What external services are used in GatherPress? =
>
>We utilize Open Street Maps to render meeting locations in a map form.  In order to do so we send the address to OSM in order to render their map.
>
>etc...

including the mentioned links.

**Comment by carstingaxion** [comment]
A fast research reveals, that there might still be a misunderstanding at the plugin review process AND our interpretation. 

For example, the following plugins are NOT providing any terms-of-service or privacy links AT ALL:

- [WP Map Block – Gutenberg Map Block for Google Map and OpenStreet Map – WordPress plugin | WordPress.org](https://wordpress.org/plugins/wp-map-block/)
- [The Events Calendar – WordPress plugin | WordPress.org](https://wordpress.org/plugins/the-events-calendar/)
- [Leaflet Map – WordPress plugin | WordPress.org](https://wordpress.org/plugins/leaflet-map/)
- [Geolocation – WordPress plugin | WordPress.org](https://wordpress.org/plugins/geolocation/)
- [Simple Location – WordPress plugin | WordPress.org](https://wordpress.org/plugins/simple-location/)
- [OSM – OpenStreetMap – WordPress plugin | WordPress.org](https://wordpress.org/plugins/osm/)

Maybe the .org plugin review team just stumbled upon `'PRODID:-//GatherPress//RemoteApi//EN',` which is a part of the iCal standard to write it that way, _I think_. This is not a reference to an external service.

**Comment by carstingaxion** [comment]
>You gather all technical/dev information to be added/modified/removed

For the beginning I _just_ moved all dev-related docs into separate file, which can be updated in the future. For now and to get the plugin into the repo, I think we better go on with the essentials.

**Comment by carstingaxion** [comment]
I made some screenshots. Which ones, what else and how many should we use?

|  |  |  |  |
|--------|--------|--------|--------|
| ![Bildschirmfoto vom 2024-05-04 14-52-50](https://github.com/GatherPress/gatherpress/assets/198883/90d366be-dd4b-4962-834c-2acc9980f2bd) | ![Bildschirmfoto vom 2024-05-04 14-53-15](https://github.com/GatherPress/gatherpress/assets/198883/6b9f3bb0-8fdf-4df7-b337-a3bd87f8287a) | ![Bildschirmfoto vom 2024-05-04 14-53-28](https://github.com/GatherPress/gatherpress/assets/198883/69992a92-40da-4e0c-9343-4781809b2702) | ![Bildschirmfoto vom 2024-05-04 14-53-58](https://github.com/GatherPress/gatherpress/assets/198883/85c53f05-c874-42f3-b59a-eec02d3e6b6c) |
| ![Bildschirmfoto vom 2024-05-04 14-54-11](https://github.com/GatherPress/gatherpress/assets/198883/b6f34700-b080-40fa-8a22-e5d2eb87ce68) | ![Bildschirmfoto vom 2024-05-04 14-55-14](https://github.com/GatherPress/gatherpress/assets/198883/b02f6e65-42e7-40a6-98fe-05464bc5bc57) | ![Bildschirmfoto vom 2024-05-04 14-55-34](https://github.com/GatherPress/gatherpress/assets/198883/d9d43c3b-e7d7-4f43-8e0f-bbd9ea51456c) | ![Bildschirmfoto vom 2024-05-04 14-57-03](https://github.com/GatherPress/gatherpress/assets/198883/163273a1-860a-4ce7-a97b-fe453ea1d759) |
| ![Bildschirmfoto vom 2024-05-04 14-57-22](https://github.com/GatherPress/gatherpress/assets/198883/8a874287-df95-417a-b025-b418cb70e4e3) | ![Bildschirmfoto vom 2024-05-04 14-57-31](https://github.com/GatherPress/gatherpress/assets/198883/e8c2daa5-6175-486a-a8a6-01ddcb64c264) | ![Bildschirmfoto vom 2024-05-04 14-57-53](https://github.com/GatherPress/gatherpress/assets/198883/e435b4c4-81a3-4107-bbe8-e76750667f75) |  |

_And yes_, I'm going to polish the edges before committing the files.

Or do we want something more fancy, like I tried with the backgrounds [here](https://github.com/carstingaxion/gatherpress-demo-data)?

![](https://raw.githubusercontent.com/carstingaxion/gatherpress-demo-data/main/assets/gatherpress-demo-data-playground.png)

**Comment by carstingaxion** [comment]
> Update the description of the GatherPress repo from the No description, website, or topics provided. placeholder to GatherPress, powering our community's event management needs. or something like that.

This is one is a _10-seconds-to-be-done-job_, for someone with writing-access to this repo. @MervinHernandez or @mauteri , could one of you please help here?

**Comment by carstingaxion** [comment]
I would suggest merging the existing _**Credits**_ section into the default `readme-file-header` and list all contributors only there.

**Comment by mauteri** [comment]
> > Update the description of the GatherPress repo from the No description, website, or topics provided. placeholder to GatherPress, powering our community's event management needs. or something like that.
> 
> This is one is a _10-seconds-to-be-done-job_, for someone with writing-access to this repo. @MervinHernandez or @mauteri , could one of you please help here?

Done.

**Comment by mauteri** [comment]
> I would suggest merging the existing _**Credits**_ section into the default `readme-file-header` and list all contributors only there.

There's a CLI script that generates output of contributors. Currently it calls WP to get profile info and generates an array of profile information to display under Settings -> Credits. Maybe we can revisit this and create an .md file (as well as or instead of).

**Comment by carstingaxion** [comment]
> > I would suggest merging the existing _**Credits**_ section into the default `readme-file-header` and list all contributors only there.
> 
> There's a CLI script that generates output of contributors. Currently it calls WP to get profile info and generates an array of profile information to display under Settings -> Credits. Maybe we can revisit this and create an .md file (as well as or instead of).
> 
> data files can be found in `gatherpress/includes/data/credits`

Yes, let us change the CLI to also update the README.md file with the wp.org profile-handles. This is something, that probably needs its own issue.

**Comment by carstingaxion** [comment]
> I would suggest merging the existing _**Credits**_ section into the default `readme-file-header` and list all contributors only there.

What I meant was more a try to simplify and DRY out the existing README. Don't get me wrong, I really, really like and appreciate showing who contributed and giving props to all the people, but the current duplication is not that nice, I think.

wp.org, takes all the handles from the file-header to create this list:
![grafik](https://github.com/GatherPress/gatherpress/assets/198883/155fadf8-9dea-4847-bad9-d714fd6430c8)

github shows a similar list, based on the git history:
![grafik](https://github.com/GatherPress/gatherpress/assets/198883/5f9d3517-89df-4b60-b9fe-d7b7e1b55f65)

The listing of wp.org profile links seems to be redundant. Let us remove the **_Credits_** section!

**Comment by carstingaxion** [comment]
>I made some screenshots.
>
>Which ones, what else and how many should we use?

Olá @patriciabt , I guess you are full in with WCEU preparation, but I'd love to read your thoughts on [the images](https://github.com/GatherPress/gatherpress/issues/406#issuecomment-2094184821). 

If you could take the time, it would be very nice.
Thanks!

**Comment by carstingaxion** [comment]
Another thing that came to my mind was WordPress‘ Code of conduct. Did you - as the GatherPress team - talked or even decided anything related to any kind of community-rules?

I’d like suggest adding another short paragraph to „Contributing“ like this:

> Please note that this project is adapting the [Contributor Code of Conduct](https://learn.wordpress.org/online-workshops/code-of-conduct/) from WordPress.org even though this is not a WordPress project. By participating in this project you agree to abide by its terms.

**Comment by mauteri** [comment]
@carstingaxion yes, please add that. Thx!

**Comment by mauteri** [comment]
> > I would suggest merging the existing _**Credits**_ section into the default `readme-file-header` and list all contributors only there.
> 
> What I meant was more a try to simplify and DRY out the existing README. Don't get me wrong, I really, really like and appreciate showing who contributed and giving props to all the people, but the current duplication is not that nice, I think.
> 
> wp.org, takes all the handles from the file-header to create this list: ![grafik](https://private-user-images.githubusercontent.com/198883/330074702-155fadf8-9dea-4847-bad9-d714fd6430c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDAyOTYsIm5iZiI6MTcxNjAzOTk5NiwicGF0aCI6Ii8xOTg4ODMvMzMwMDc0NzAyLTE1NWZhZGY4LTlkZWEtNDg0Ny1iYWQ5LWQ3MTRmZDY0MzBjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxMzQ2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzYwYmFhOThiMzk2NzMxMGEzYzRhNGNkMTg4OGUwZmNhYTlhMGVkMTJhNmFmYWI4ZTI2MDFhMDA5Y2Y5MWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tfbgW9pnVG0WBaqfWqcqZrP7o0ioBtXP8BhN3a-m3N8)
> 
> github shows a similar list, based on the git history: ![grafik](https://private-user-images.githubusercontent.com/198883/330074951-5f9d3517-89df-4b60-b9fe-d7b7e1b55f65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDAyOTYsIm5iZiI6MTcxNjAzOTk5NiwicGF0aCI6Ii8xOTg4ODMvMzMwMDc0OTUxLTVmOWQzNTE3LTg5ZGYtNGI2MC1iOWZlLWQ3YjdlMWI1NWY2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQxMzQ2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzdlNTc5NWM5ZGM3MjA3YTM1OTQ2NGRiNGVjYjdiYjRhN2E3MzdkYjY0ZDM5ZGI2MjE0MmQxODM0M2NlYzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W15m9eAx8foY_yWgqLfSrqV8GO7jmUaUjdt1M66KvNo)
> 
> The listing of wp.org profile links seems to be redundant. Let us remove the **_Credits_** section!

@carstingaxion yes, we can remove that section from readme. That is fine. For the CLI script I'll manage the README.md to be populated by the CLI script that also creates the credits section within the plugin. Thx!
