### ISSUE TITLE
Revisit Attendance Block

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#41]

**Comment by MervinHernandez** [comment]
#1 . Mike will take a peek at CSS
#2. Mervin & Ana will come to it, and update the design for when the status changes

**Comment by mauteri** [comment]
Screenshots of meetup.com flow.

<img width="465" alt="1" src="https://user-images.githubusercontent.com/818980/153776093-d931288b-3789-4ac7-aeaf-0492c67d7ace.png">
<img width="556" alt="2" src="https://user-images.githubusercontent.com/818980/153776091-eead09bb-daca-4c57-9d26-692bd7af6710.png">
<img width="563" alt="3" src="https://user-images.githubusercontent.com/818980/153776090-5dce4da2-61c8-4b11-aa04-b00df235b44e.png">
<img width="342" alt="4" src="https://user-images.githubusercontent.com/818980/153776089-efb3182a-e799-4be2-a7f2-e052b5991b3f.png">
<img width="540" alt="5" src="https://user-images.githubusercontent.com/818980/153776088-2f26b32f-410c-4921-8eca-a7e93c276372.png">

**Comment by mauteri** [comment]
@MervinHernandez initial work is done. Will do some cleanup, but this should be much more functional now.
