### ISSUE TITLE
ADD Action Flush Permalinks on activation

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#44]
Upon activating plugin - flush permalinks.

**Comment by MervinHernandez** [comment]
@pbrocks is this still on your radar my friend?

**Comment by MervinHernandez** [comment]
@pbrocks is this just `add_action('init','rewrite_flush()')` ... or something else is needed?

**Comment by pbrocks** [comment]
Mike did this

**Comment by mauteri** [comment]
I don't think I did... I was leaving this one for you.

**Comment by pbrocks** [comment]
@mauteri @MervinHernandez https://github.com/GatherPress/gatherpress/pull/136

**Comment by pbrocks** [comment]
Looks like [this](https://github.com/GatherPress/gatherpress/pull/167) takes care of it. I suggest closing this Issue, @MervinHernandez

**Comment by pbrocks** [comment]
@MervinHernandez @mauteri Let's close
