### ISSUE TITLE
Update .pot and translations for 0.28.0

### ISSUE THREAD

**Issue by patriciabt** [GatherPress/gatherpress#538]
Create new .pot file for 0.28.0
Update
fr_FR @patriciabt
es_ES @javiercasares 
ca @moranjosep
de_DE @CoachBirgit

**Comment by patriciabt** [comment]
Until my pull request is merged, you can find the new gatherpress.pot on my repo
https://github.com/patriciabt/gatherpress/blob/default/languages/gatherpress.pot

@javiercasares
@moranjosep
@CoachBirgit

**Comment by patriciabt** [comment]
Now merged, the new [gatherpress.pot](https://github.com/GatherPress/gatherpress/blob/main/languages/gatherpress.pot) is here under languages

**Comment by patriciabt** [comment]
Thank you @carstingaxion 
I informed @coachbirgit that you did the formal de_DE translation.
I will create the .json files for you (necessary for texts in blocks)
Could you create a Pull request for the German .po/.mo files to be merged here? Thx!
Anyway, as soon as GatherPress is accepted in the official plugin repository, those steps won't be necessary anyore and we'll be able to translate on translate.wordpress.org

**Comment by carstingaxion** [comment]
You're welcome @patriciabt .

Don't worry about the json files, I'll create them on the go either. But Thanks, very kind.

Opening a PR would be a pleasure to me.

Dear @CoachBirgit, I already started on both, de_DE and de_DE-formal, maybe you'd like to proofread and polish my (coming) PR?

**Comment by patriciabt** [comment]
oh you did both German and Formal German, sorry I hadn't seen!
Ok if you can create the .json files for both and a pull request, then it's in the 0.28.0 version that will be built very soon!
Thx a lot

**Comment by moranjosep** [comment]
The chains in the Catalan language have already been made, greetings.
