### ISSUE TITLE
Allow for easier translation

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#551]
### Is your enhancement related to a problem? Please describe.

Some strings within the code base are concatenated from 2 or more *source strings*. This makes it hard for translators to get the context of a string and even work out the grammar correctly. Some languages might even need a different sentence order, than what GP provides, which would be impossible.

 This could be improved by using [sprintf](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-i18n/#sprintf) more often. 

Some examples:

- https://github.com/carstingaxion/gatherpress/blob/1ed3fb75952e8da2e87aa93e11c72bd50e1248c4/src/components/Rsvp.js#L184-L188
- https://github.com/carstingaxion/gatherpress/blob/dfb7621bd567db49b9332ee0517726e5e613ae3e/src/components/Rsvp.js#L192-L198
- https://github.com/carstingaxion/gatherpress/blob/dfb7621bd567db49b9332ee0517726e5e613ae3e/includes/templates/admin/setup/membership-check.php#L12-L15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patriciabt** [comment]
Hello, 
I created the .pot file with this WP-CLI command
https://developer.wordpress.org/cli/commands/i18n/make-pot/

if there is anything I need to do differently, please tell me!

Furthermore, this is a temporary thing, as GatherPress should be accepted on the WordPress plugin repository very soon (probably even in a few days) so I believe that GlotPress (on translate.wordpress.org) will create the .pot file automatically. Once there, you'll be able to upload your German .po files the first time then continue submitting translations there.

Thank you so much for your work

**Comment by carstingaxion** [comment]
>if there is anything I need to do differently, please tell me!

No, really not. I think you are doing fine ... btw. I used the same `wp cli` command.

The **small** problem here is in the code itself and @mauteri or me or one of the other code-contributors can easily fix this, I guess.

**Comment by patriciabt** [comment]
As a note
https://make.wordpress.org/core/2024/02/27/i18n-improvements-6-5-performant-translations/
