### ISSUE TITLE
Implement Open Street Map

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#561]
Based on discussion on February 23, this ticket is to 
1. ~Deprecate Google Maps~
2. Implement Open Street Map

---

# Deliverables
> last updated June 15
- [ ] Smooth rendering of an address on the front-end (via OSM)
- [ ] Test layout visibility on desktop + mobile (responsive)
- [ ] Add new meta field for `lat-long`
- [ ] **Added requirement**: UPON Saving a venue then resolve the venue addresses to lat-long values via OpenStreet Maps in meta.
- [ ] Test toggle between Google Maps + Ensure no breakage of Google Maps 
- [ ] Update the readme file (upon merge)

**Comment by jesusyesares** [comment]
Hi, have you considered the possibility of implementing Leaflet.js?  It has Open Street Map and other base maps, and It could add other possibilities.

;)

**Comment by patriciabt** [comment]
Thank you @jesusyesares 
(for @mauteri, Jesús is THE map expert)

**Comment by mauteri** [comment]
I'm open to this! 😊

**Comment by jesusyesares** [comment]
Not so much, I was the map expert in a moment of the history. Now I'm only learning. But I have explored some map projects and leaflet it's the more flexible probably. Map Libre would be another option too.

**Comment by pbrocks** [comment]
@jesusyesares TBH, I had actually explored Leaflet and Mapbox as potential solutions when initially implementing the maps feature. My recollection for passing on it at the time was that it required some decision-making for settings that were beyond the core features of GatherPress at the time. Happy to revisit and implement if reasonable enough to do so.

**Comment by mauteri** [comment]
@pbrocks let's discuss Friday, thx Paul!

**Comment by stephenerdelyi** [comment]
Hi all, just put in a working PR for this - @jmarx and I are working on the implementation and look forward to sharing updates in our upcoming meeting https://github.com/GatherPress/gatherpress/pull/643

**Comment by MervinHernandez** [comment]
# 🚩 June 15 Review
✅ Updated the objectives for this ticket
✅ Discussed front-end leaflet
* Added requirement = UPON Saving a venue then resolve the venue addresses to lat-long values via OpenStreet Maps in meta.
* Steve is working on it as we speak // Expected EOD milestone

**Comment by stephenerdelyi** [comment]
Just noting we're in the final stages of this task. Polishing up / fixing small bugs as we find them.

**Comment by MervinHernandez** [comment]
# 🚩  June 22 Review

Acknowledged this is in flgith.

**Comment by MervinHernandez** [comment]
@carstingaxion @jmarx where are we gathering the latest code for this feature, which I can review/test?

**Comment by carstingaxion** [comment]
> @MervinHernandez where are we gathering the latest code for this feature, which I can review/test? 

It's over here: https://github.com/GatherPress/gatherpress/pull/643
