### ISSUE TITLE
No location set; Results in Map shows: 60 29th St, San Francisco, CA 94110, USA

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#568]
This is showing up on Front End too and should be fixed ONLY to show up on backend when using FSE to add the block to a template.

**Comment by stephenerdelyi** [comment]
@mauteri you cool if I take this one?

**Comment by mauteri** [comment]
@stephenerdelyi have at it. thx! 

Change the default address also to WordPress Foundation per @patriciabt which is more appropriate.

660 4th Street #119
San Francisco CA 94107
