### ISSUE TITLE
javascript conflict

### ISSUE THREAD

**Issue by shawfactor** [GatherPress/gatherpress#602]
### Describe the bug

The dependencies to 'gatherpress-admin' seem to cause conflicts with wp log viewer and geerate javascript errors, it may be that they are enqueued too early. I am not sure the exact issue but the error is listed below. I will raise it with wp-log viewer too but is 'gatherpress-admin' required in all admin contextst

What is 'gatherpress-admin' used for? Does it need to be enqueued in all backend screens? Even if gatherpress is doing this right (and I suspect it is) and the other plugin is in error. I think it makes sense to only enqueue javascript it where it is required, especially react which seems very brittle.

Uncaught Error: Invariant Violation: App.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
    r https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    _renderValidatedComponent https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:2
    a https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    _updateRenderedComponent https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:2
    _performComponentUpdate https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:2
    updateComponent https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:2
    a https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    performUpdateIfNecessary https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:2
    performUpdateIfNecessary https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    s https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    perform https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    perform https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    perform https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    x https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    a https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    closeAll https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    perform https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    batchedUpdates https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:3
    l https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    r https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    enqueueSetState https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    setState https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:2
    componentWillMount https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:7
    success https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:6
    handleReadyState https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    getRequest https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    init https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:6
    Reqwest https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    reqwest https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:6
    e https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:9
    getAllEntries https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:9
    componentWillMount https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:7
    mountComponent https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:2
    a https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    mountComponent https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    h https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    perform https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    m https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    perform https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:5
    batchedUpdates https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:3
    a https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    _renderNewRootComponent https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    a https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    render https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    a https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:4
    <anonymous> https://princesparktouch.com/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=6.4.3:9
main.min.js:5:21515

### Steps to Reproduce

Go wo wp-admin
use wp-log viewer
It does not work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
> Does it need to be enqueued in all backend screens? [...] I think it makes sense to only enqueue javascript it where it is required,

Absolutely @shawfactor, I thought the same today.

**Comment by carstingaxion** [comment]
Hello @shawfactor,

I had another look into this issue; scanning through your long list of mentioned files, I can't see any reference to GatherPress. 
**Can you provide more information, why your problem should be related to GatherPress?**

---

Meanwhile I opened #636 to bring some attention to the second aspect here: the needless enqueing of js and css files.

**Comment by shawfactor** [comment]
Carsten there is only one file where the error occurs ( the error repeats itself). I think there is some conflict with that file (which is not gatherpress) and gatherpress admin.js. As where I dequeue admin.js there is no error

only enqueueing assets where appropriate would fix my problem (and speed up admin experience marginally)

**Comment by carstingaxion** [comment]
Hello @shawfactor 

Can you provide a screenshot or screenrecording that shows how and where "the error repeats itself"?
_This would help me._

**Comment by mauteri** [comment]
@shawfactor @carstingaxion this might be able to be closed. I think we did away with the gatherpress-admin JS in a recent version. Other than some admin styles, other scripts/styles are specified within conditionals. https://github.com/GatherPress/gatherpress/blob/main/includes/core/classes/class-assets.php#L138

**Comment by shawfactor** [comment]
Yes I think it can be closed

Pete

**Comment by mauteri** [comment]
Great, thanks. If you see it pop up again please reopen.
