### ISSUE TITLE
Convert add-to-calendar into interactive button block-variation 

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#606]
### Is your enhancement related to a problem? Please describe.

Everything that looks like a button, should behave like a button (within the WordPress editor).

To allow for individual styling and also to remove some maintenance burden on the GatherPress side, I recommend converting the existing `add-to-calendar` block into a block-variation of the core `button` block.

Currently this block has minimal interactivity already implemented, which could be a perfect fit to further explore using the new Interactivity API (publicly rolled out in WP 6.5).

### Designs

**You can test the block within the [GatherPress Block Playground](https://github.com/carstingaxion/gatherpress-block-playground)**

Using the [wordpress/create-block package with a new *interactivity* template](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-interactivity/#scaffold-an-interactive-block), we instantly get 50% of our needs already delivered - a button, that reveals some more content on click.

1. Calling this ...
    ```console
   npx @wordpress/create-block@latest gatherpress-interactive-block --template @wordpress/create-block-interactive-template
   ```
2. Creates this 

   https://github.com/GatherPress/gatherpress/assets/198883/cf8c46ed-4b27-4fa5-a930-f975d99bee57
  
3. Which should be relatively easy to adopt to our needs ... **Let's go!**

### First questions & findings
- [ ] Can we add `"supports": {"interactivity": true }` to only a variation of a block rather than all of a block-type?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
This doesn't took too long. 

Still without using the _Interactivity API_ at all, **but working!**


https://github.com/GatherPress/gatherpress/assets/198883/36ad63ad-035c-4cee-9334-93645f7c8c43

**Comment by carstingaxion** [comment]
# This is very exciting!

I’ve made good progress and would call it *Enhanced feature parity*. My new implementation of the *Add to calendar* Block is a *button* block under the hood. So you can use every of the default controls for normal button blocks, as long as your theme allows you to.

Besides that I made sure that all of the existing functionality is ported into the new block.

## I called it *Enhanced*, because the new block (variation) …

- [x] can be transformed from a usual button block into our special one
- [x] removes the LinkControl UI from the blocks’ Toolbar
- [x] uses most of the style properties to make the submenu, match the button style

## Open todos

- [ ] Make sure this is accessible. Right now with the used `display:none;` and the `div`-based markup this seems not accessible to me, but I’m neither an expert nor have I done any testing on this.
- [ ] Modify existing tests and write new ones
- [ ] Open a PR


### This could still be improved by

- making the submenu a somehow editable `innerBlocks` component, which would benefit to individual styling and text-editing as well
- removing the *CSS Class* panel from the `InspectorControls`, which is (IMHO) only possible on the blockType level
- using the Interactivity API, but instead it currently relies on the existing, small piece of custom JS.

**Comment by carstingaxion** [comment]
This is my current exploration repo:
https://github.com/carstingaxion/gatherpress-add-to-calendar

[Install the .zip-file](https://github.com/carstingaxion/gatherpress-add-to-calendar/archive/refs/heads/main.zip) and have a look, if you want.

**Comment by carstingaxion** [comment]
>Because by the nature of a core/button block this can only be inserted inside a core/buttons block. This leads to, the new block (variation) will be invisible within the blockInserter and also from the blockAppender, the "+" button. Additionally our block will not be selectable from within our gatherpress block-category.

**Solved**

I defined another block-variation, this time one of the `core/buttons` block. This one gets our new variation set as an `innerBlock`. And it gets *no* `isActive` property at all, by doing so we create a kind of honeypot-, trap- or pseudo-block.

This pseudo-block that has the same name, description and icon like our new block, but once inserted into the editor it becomes a pure normal `core/buttons` block, because of the missing `isActive` prop the editor is not able to recognize our pseudo-block. 

And voila, we can select our *Add to calendar* block from all possible spots.

**Comment by carstingaxion** [comment]
After I read through [Thoughts on the WordPress Interactivity API](https://permanenttourist.ch/2024/02/thoughts-on-the-wordpress-interactivity-api/) by @markhowellsmead I wanted to make sure, we're not running into a new and maybe overseen performance issues. 

So I tested the existing block against my new block from the [interactivity-api](https://github.com/carstingaxion/gatherpress-add-to-calendar/tree/interactivity-api) branch of my exploration plugin.

Luckily the results show nothing to worry about. 
We're getting even slightly better in the amount of kb transferred. 

| Old | New |
|--------|--------|
| ![Bildschirmfoto vom 2024-03-17 16-08-41](https://github.com/GatherPress/gatherpress/assets/198883/27a4151c-81c7-4ae2-862b-7a6e3ab0050f) | ![Bildschirmfoto vom 2024-03-17 16-24-29](https://github.com/GatherPress/gatherpress/assets/198883/23272f25-8357-4e1f-83e8-0d2cfe73c80e) |

**Comment by MervinHernandez** [comment]
✅ Viewed 606 - Convert custom block to Gutenberg block variation - Carsten has it

**Comment by carstingaxion** [comment]
- [ ] close the _submenu_, when clicking somewhere else

**Comment by carstingaxion** [comment]
👀

> it is possible to use a custom webpack.config.js file and the `-experimental-modules` flag

https://developer.wordpress.org/news/2024/04/11/a-first-look-at-the-interactivity-api/#comment-5685

**Comment by carstingaxion** [comment]
The new (and also the old) block do not let me download iCal or outlook files on iPadOs 17.5.1

https://github.com/GatherPress/gatherpress/assets/198883/5fbbfcec-0571-4f74-a433-677a79dc5a68

**Comment by MervinHernandez** [comment]
✅ Reviewed June 22 - Kudos on progress @carstingaxion

**Comment by carstingaxion** [comment]
> ✅ Reviewed June 22 - Kudos on progress @carstingaxion

Thanks @MervinHernandez !

**Comment by carstingaxion** [comment]
No matter if on a theatre stage during rehearsal or in software development, every art knows:

# Kill your darlings

That's why I would like to drop my matured proposoal of an _interactive_ Add-to-calendar block, in favor of a much simpler _non-interactive_ Add-to-calendar block.

After some while that I tested and figured out a `core/button` block-variation with some Interactivity API on top, I realised that things could be way easier. I stepped back another time and explored alternatives for that block.

https://github.com/GatherPress/gatherpress/assets/198883/e1a9fe76-7951-4097-a01f-bef5f3351b37

From top to bottom:

1. Current block
2. `core/button` block-variation with some Interactivity API on top
3. `core/details` & `core/button` block-variations using the block-bindings API
4. Using a `core/navigation` block

## Variant number 3 turned out to be the best of the four, because:

- uses only core blocks
- is 100% flexible in design and layout, depending on theme and editors choice
- needs zero JS on the frontend
- is the most accessible solution (from the 4 options)

I added this as an alternate Add-to-calendar block to the [GatherPress Block Playground](https://github.com/carstingaxion/gatherpress-block-playground). Due to my lack of time, this block is not yet used in any patterns or templates, but is available from the block inserter with `Add to calendar (DETAILS)` 

![grafik](https://github.com/GatherPress/gatherpress/assets/198883/a7551093-fe91-4d4f-b771-c775aedd2f34)

I also added a block-style to provide an icon, like the current implementation does. (https://github.com/GatherPress/gatherpress/issues/631#issuecomment-2185347515)

**Give it a try & tell me what you think, please!**
