### ISSUE TITLE
WP.ORG: Undocumented use of a 3rd Party or external service

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#610]
We permit plugins to require the use of 3rd party (i.e. external) services, provided they are properly documented in a clear manner.

We require plugins that reach out to other services to disclose this, in clear and plain language, so users are aware of where data is being sent. This allows them to ensure that any legal issues with data transmissions are covered. This is true even if you are the 3rd party service.

In order to do so, you must update your readme to do the following:
Clearly explain that your plugin is relying on a 3rd party as a service and under what circumstances
Provide a link to the service .
Provide a link to the service terms of use and/or privacy policies.
Remember, this is for your own legal protection. Use of services must be upfront and well documented.

Example(s) from your plugin:
# Domain(s) not mentioned in the readme file.
21_21-26-52_gatherpress/includes/core/classes/class-event.php:812 $args = array(
'BEGIN:VCALENDAR',
'VERSION:2.0',
'PRODID:-//GatherPress//RemoteApi//EN',
'BEGIN:VEVENT',
sprintf( 'URL:%s', esc_url_raw( get_permalink( $this->event->ID ) ) ),
sprintf( 'DTSTART:%s', sanitize_text_field( $datetime_start ) ),
sprintf( 'DTEND:%s', sanitize_text_field( $datetime_end ) ),
sprintf( 'DTSTAMP:%s', sanitize_text_field( $datetime_stamp ) ),
sprintf( 'SUMMARY:%s', sanitize_text_field( $this->event->post_title ) ),
sprintf( 'DESCRIPTION:%s', sanitize_text_field( $description ) ),
sprintf( 'LOCATION:%s', sanitize_text_field( $location ) ),
'UID:gatherpress_' . intval( $this->event->ID ),
'END:VEVENT',
'END:VCALENDAR',
);

**Comment by shawfactor** [comment]
I’m confused What third party service is the code generating the vCard using?

**Comment by mauteri** [comment]
> I’m confused What third party service is the code generating the vCard using?

I'm assuming they are referring to Google & Yahoo! calendar events. That's how I interpreted it.

**Comment by shawfactor** [comment]
That is possible but that is not part of the code detailed which is ical, an open format.

might want clarify, also if so then google maps would also fall within the issue. 

The events calendar just lists the functionality in the readme so likely that is all that is required.

**Comment by mauteri** [comment]
@stephenerdelyi @jmarx @jeffpaul can you guys take a look at this one? Thx!

**Comment by jeffpaul** [comment]
I'm guessing their review hinges on the `'PRODID:-//GatherPress//RemoteApi//EN',` bit, but I'll admit to not know what external services are utilized across the codebase.  I'm also not aware of this plugin review team requirement, I've not seen it on ANY of the plugins I've worked on and I know at least some utilized an external service.  That said, if you're able to lists what external services are bundled in GP then perhaps adding an FAQ on that would suffice.

Example:
```
= What external services are used in GatherPress? =

We utilize Open Street Maps to render meeting locations in a map form.  In order to do so we send the address to OSM in order to render their map.

etc...
```
