### ISSUE TITLE
Request for managing & assigning GitHub labels

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#627]
### Describe your question

With more and more issues created I’d like to be able to filter them easier, that’s why I would love to add additional labels to some of our issues.

I’m not sure this is allowed for [outside collaborators](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-user-access-to-your-organizations-repositories/managing-outside-collaborators), but it would be nice if anyone with access to the organisation’s settings could have a look.

If there is no way, I would suggest:

- converting all UPPERCASE words in issue titles into labels, e.g. WP.ORG or BLOCK.
- introducing a new label „Overview“ or „tracking“ for long term stuff

I really like the way issues are organised within the Gutenberg repository, where often a label consists of two parts for example „BLOCK: Query“. I can imagine some of these labels for GatherPress as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
Further on I’d like to suggest:

- a „could-be-re-used-for-documentation“ label, that could help identify issues with content, that could be understood by non-developers, to be used for the FAQ of the readme.txt or the gatherpress.org website
- an „idea“ label for everything that is nice to have later on; alternatively we could make use of the GitHub discussions feature, which would allow for the same kind of separation

**Comment by carstingaxion** [comment]
Hello @patriciabt and @mauteri ,

could I please get your attention over here?

While working on all the blocks, it would help, if I could assign some labels to GitHub Issues, like described here. 

Some time ago I’ve heard about the _triage role_ within a GitHub Organisation. Maybe you could assign that role to me, please?!

**Comment by carstingaxion** [comment]
Hooray 😃 and thank you for the invitation @mauteri !

😎🚀🌈🎉❤️

**Comment by carstingaxion** [comment]
Oops. Celebrated too early.

Now I’m able to assign labels, which is cool and halfway.

But I’m not allowed to create such. Because I’m unsure about other roles, maybe it’s just easier to get the labels added by someone with permissions.

I would suggest at least the following (in addition to what I wrote before):

- blocks
- gatherpress.org
- tracking 

@mauteri please?!

**Comment by carstingaxion** [comment]
This problem have a looooong story https://github.com/isaacs/github/issues/148

**Comment by mauteri** [comment]
@carstingaxion @MervinHernandez @patriciabt let's discuss labels we need: some already suggested, plus others like `accessibility` (which was suggested in our call with WP accessibility specialists).

**Comment by mauteri** [comment]
@carstingaxion actually I see labels now. Can this ticket be closed?
