### ISSUE TITLE
 General changes to post type registrations and registration of two new invisible patterns

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#628]
### Is your enhancement related to a problem? Please describe.

Gaining for greater flexibility, I'd like us to encourage the Block Hooks API to add all of the GatherPress blocks into templates.
Following on, with what I wrote at https://github.com/GatherPress/gatherpress/issues/626

>Therefore GatherPress registers two invisible block patterns, that are used as template properties of the main post types.

1. Within my [exploration](https://github.com/carstingaxion/gatherpress/tree/feature/experimental-query-block) I changed the `template` property to the following: 

  ```php
  'template'     => array(
	  // array( 'gatherpress/venue' ),
	  array( 'core/pattern', array( 'slug' => 'gatherpress/venue-details' ) ),
  ),
  ```

2. The called pattern looks like this and will not be visible to the editor at any point:

  ```php
  \register_block_pattern( 'gatherpress/venue-details',
	  array(
		  'title'         => 'Invisible Venue Details Block Pattern', // no i18n needed
		  'content'       => '', // this will a be hooked ;)
		  'inserter'      => false,
		  'source'        => 'plugin',
	  )
  );
  ```

3. Now any block - inside and outside of the GatherPress plugin - can easily declare:

```php
add_filter( 'hooked_block_types', __NAMESPACE__ . '\\hook_block_into_pattern', 10, 4 );
function hook_block_into_pattern( $hooked_block_types, $relative_position, $anchor_block_type, $context ) {
	if (
		// Conditionally hook the block into the "gatherpress/venue-details" pattern.
		is_array( $context ) &&
		isset( $context[ 'name' ] ) &&
		'gatherpress/venue-details' === $context[ 'name' ]
	) {
		$hooked_block_types[] = 'gatherpress/rsvp';
	}
	return $hooked_block_types;
}
```

4. It just gets a little messy when it comes to block variations, that use the Block Bindings API under the hood.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
The described changes are already part of https://github.com/carstingaxion/gatherpress/pull/25

**Comment by MervinHernandez** [comment]
✅ Viewed 628 - GB Standards compliance - Carsten has it

**Comment by carstingaxion** [comment]
I wanted to test the [new Event Query block](https://github.com/GatherPress/gatherpress/issues/599) within the normal template hierachy, but was not able to create an archive template.
![Bildschirmfoto vom 2024-06-16 23-04-43](https://github.com/GatherPress/gatherpress/assets/198883/2eb935ef-a5b9-4eb2-ada0-3d02711599df)


until I added the following (for testing) to the post type registration:
```php
'has_archive'   => true,
```
which allowed me to create an archive template.
![Bildschirmfoto vom 2024-06-16 23-08-36](https://github.com/GatherPress/gatherpress/assets/198883/ec68c87a-6da2-4a62-b190-5d2d626d669c)


@mauteri and @MervinHernandez  Please let me know, if it is a decision by pupose or somehow needed for the existing `general['pages']` setting, that `gatherpress_event` should not have a post type archive?

**Comment by mauteri** [comment]
@carstingaxion that may have been done because of sorting being done by publish date, but I don't 100% recall.... if it's need for Event Query, then add the `has_archive => true`

**Comment by MervinHernandez** [comment]
@carstingaxion I am also unsure why this was not set to true. I support declaring it as `true`.

**Comment by carstingaxion** [comment]
Thank you both @mauteri and @MervinHernandez for your feedback. I appreciate your answers and made the discussed change in https://github.com/carstingaxion/gatherpress/commit/062aceb65b6aef6b9fd7a428777b5ed6fbdd3233

Unfortunately I had no time to test, creating an archive template using the block, yet. But will do in 2 weeks, when we are back from family holiday.

The branch with the change powers the [GatherPress Block Playground](https://github.com/carstingaxion/gatherpress-block-playground), so feel free to test it yourself if you want.
