### ISSUE TITLE
Allow backslashes in date format

### ISSUE THREAD

**Issue by nilovelez** [GatherPress/gatherpress#632]
### Describe the bug

The default date for WordPress in es_ES is "j \d\e F \d\e Y", which should render as "4 de marzo de 2024"

In GatherPress it shows as "4 DDzz marzo DDzz 2024" because it escapes the backslashes in the date format.

### Steps to Reproduce

1. Go to Events > Settings and set the date format as "j \d\e F \d\e Y"
2. Create an event

### Screenshots, screen recording, code snippet

![image](https://github.com/GatherPress/gatherpress/assets/1619760/244f0d29-c422-4b24-99c8-ad512b1a2f17)
![image](https://github.com/GatherPress/gatherpress/assets/1619760/3c4e8c56-1bba-4ab3-8856-d017ba18e565)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
Hello @nilovelez,

I found the bug, fixed it and proposed it for merge at #637

Good night

**Comment by nilovelez** [comment]
Great, thank you!
