### ISSUE TITLE
Venue choice not being selected in the body of the event post

### ISSUE THREAD

**Issue by jmarx** [GatherPress/gatherpress#640]
### Describe the bug

When selecting a venue for an event, the selected venue choice currently does not switch in the body of the post.

<img width="1468" alt="Screenshot 2024-04-06 at 12 18 58 PM" src="https://github.com/GatherPress/gatherpress/assets/223919/9b0f5b1a-6999-4635-8dfe-045d76bca7b4">

### Steps to Reproduce

- Create an event
- Select a venue
- Notice the venue choice is reflected in the sidebar, but not in the body of the event.

### Screenshots, screen recording, code snippet

<img width="1468" alt="Screenshot 2024-04-06 at 12 18 58 PM" src="https://github.com/GatherPress/gatherpress/assets/223919/f083c64f-225a-4658-b8ea-ed92edbf5c61">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
Hello @jmarx, 

as I read, that two identified errors might be the result of your session, I felt not good. "_May I have broken something within my recent changes?_" I thought.

So I made sure:

- [x] I'm running a clean version of the latest commit, which seems to be [76b097a58137402b608769876a2d2cac2d61d3a6](https://github.com/GatherPress/gatherpress/commit/76b097a58137402b608769876a2d2cac2d61d3a6).
- [x] I have only GatherPress (and the QueryMonitor) enabled
- [x] WordPress 6.5 is running

The good and the bad; I was not able to reproduce what you described.
Everything seemed to be working.

https://github.com/GatherPress/gatherpress/assets/198883/d8dfcc13-3d6f-4dee-be39-183fe0a9d25f

_**Can you please try to give some more information?**_

**Comment by jmarx** [comment]
@carstingaxion Interesting. Yeah I wasn't trying to point any fingers. @stephenerdelyi was also able to reproduce the issue during our session. Let me take another look.

**Comment by jmarx** [comment]
@carstingaxion I am running 6.5 of wp and the latest version of master and still seeing this.
<img width="679" alt="Screenshot 2024-04-07 at 2 59 26 PM" src="https://github.com/GatherPress/gatherpress/assets/223919/64dfd540-3bf0-4326-a489-2727f6b6fb62">
@MervinHernandez Can you try to reproduce this issue on gathepress.org?
Maybe I am just going crazy lol

**Comment by jmarx** [comment]
Closing this for the same reason as https://github.com/GatherPress/gatherpress/issues/641
