### ISSUE TITLE
Venue map not showing on the front end

### ISSUE THREAD

**Issue by jmarx** [GatherPress/gatherpress#641]
### Describe the bug

When selecting a venue, we are not seeing the map displayed on the front end like we used to.
<img width="1182" alt="Screenshot 2024-04-06 at 12 27 27 PM" src="https://github.com/GatherPress/gatherpress/assets/223919/00c271dd-fd6f-4b9b-9cdc-16307e8eba02">

### Steps to Reproduce

- Create an event.
- Select a venue and save the event
- Notice how we see the name of the venue on the frontend but not the map embed.

### Screenshots, screen recording, code snippet

<img width="1182" alt="Screenshot 2024-04-06 at 12 27 27 PM" src="https://github.com/GatherPress/gatherpress/assets/223919/b1089712-57a2-410d-9568-da3bfc79185e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
Luckily and unfortunately, it's the same over here @jmarx .
With [my described setup](https://github.com/GatherPress/gatherpress/issues/640), I can not reproduce the described missing map.

**Comment by jmarx** [comment]
@carstingaxion Can you send me a screengrab of the map working on your front end?
@stephenerdelyi you were also able to reproduce this, correct?

Let me take a closer look at my setup.

**Comment by jmarx** [comment]
I am also running WP 6.5 and I am getting the latest version of the plugin after the object/object issue was fixed.

I am still seeing this.

<img width="679" alt="Screenshot 2024-04-07 at 2 59 26 PM" src="https://github.com/GatherPress/gatherpress/assets/223919/73d2b35f-1c9a-46b6-a5f6-9ee819d7cd5f">


@mauteri when you get back, can you please try and reproduce?

**Comment by mauteri** [comment]
@jmarx this might be related to @stephenerdelyi update to the default map address. I'd start investigating there. It was one of the more recently merged PRs.

**Comment by stephenerdelyi** [comment]
Great callout @mauteri, I was just about to note if your test venue (Westchester Community College) does not have an address entered in the backend this is an expected result - I was able to replicate but I didn't realize I was using my test event created specifically for the task of hiding that map, apologies for that oversight!

Can you confirm if you have an address entered in the backend for that venue?

**Comment by jmarx** [comment]
@mauteri That was the case cc @stephenerdelyi I created a new venue and it wall worked.
cc @carstingaxion 
Sorry for the false alarm!

**Comment by stephenerdelyi** [comment]
Sorry for the confusion! I should have clarified that but didn't think to mention it after (incorrectly) testing on my end 🤦‍♂️

**Comment by carstingaxion** [comment]
To avoid such scenarios GatherPress could have a decent admin-only hint over there, saying that the venue has no address given. Shown in the same spot, where you expected the map.

Or GatherPress only allows to save a venue, as long as address data is given. Via the pre-publish-checklist.

**Comment by mauteri** [comment]
@carstingaxion mind putting in a ticket for that admin-only hint?
