### ISSUE TITLE
Create reusable demo data

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#649]
Let’s create a WordPress import file with typical event-data!

### Is your enhancement related to a problem? Please describe.

I’d like to create a blueprint.json to create a playground with my block variation experiments.

**A set of prepared demo data would be nice**, because it makes showcasing much easier, when everybody on the team knows the used data already.

This could additionally be used: 

- for a playground to showcase GatherPress in general 
- to prepare & use a set of data similar to the [Theme (Unit) Test Data](https://github.com/WordPress/theme-test-data)
- to power the _plugin preview Button_ playground on wp.org
- together with the ~~https://wordpress.org/plugins/interactive-code-block/~~ [playground-block](https://github.com/WordPress/playground-tools/tree/trunk/packages/wordpress-playground-block) on https://gatherpress.org/
   - to run a general showcase
   - to show demos of current development explorations within the Blog
- to create localised demo-data in multiple languages
- to introduce a workflow, which comments on PRs with a link to playground instance of that particular PR. Such a [live preview playground](https://github.com/WordPress/wordpress-playground/issues/1237) could also benefit from a standardised demo-data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

---

UPDATE: Merged all my comments into the issue-description and deleted the comments.

**Comment by carstingaxion** [comment]
> for js and php tests

We could use and prepare a set of data similar to the [Theme (Unit) Test Data](https://github.com/WordPress/theme-test-data)

And additionally we could use demo-data to power the _plugin preview Button_ playground on wp.org

**Comment by carstingaxion** [comment]
Further on we could use demo-data together with the https://wordpress.org/plugins/interactive-code-block/ on https://gatherpress.org to 

1. run a general showcase
2. and to show demos of current development explorations within the Blog.

**Comment by carstingaxion** [comment]
Some first-try demo data is already available at

https://github.com/carstingaxion/gatherpress-demo-data/blob/main/GatherPress-demo-data-2024.xml

But because it is so super-easy to [update the existing set](https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/carstingaxion/gatherpress-demo-data/main/gatherpress-demo-blueprint.json) or [create a totally new one](https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/carstingaxion/gatherpress-demo-data/main/gatherpress-blank-install-blueprint.json), everybody is invited to extend the demo-data.

More information can be found in the README and the issues of

https://github.com/carstingaxion/gatherpress-demo-data

**Comment by carstingaxion** [comment]
We could also have localised demo-data in multiple languages.

**Comment by carstingaxion** [comment]
We could introduce a workflow, which comments on PRs with a link to playground instance of that particular PR. Such a [live preview playground](https://github.com/WordPress/wordpress-playground/issues/1237) could also benefit from a standardised demo-data.

**Comment by carstingaxion** [comment]
I would call this _working_. 

To update the demo-data:

1. Open a Playground
2. Create, edit & save the data
3. Export the xml to the Playground
4. Create a PR from inside the Playground
5. Merge the PR

[<kbd> <br>Go on and test it with the demo-data, that is referenced in every GatherPress Playground.<br> </kbd>](https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/carstingaxion/gatherpress-demo-data/main/blueprints/gatherpress-save-export-to-server-blueprint.json&gh-ensure-auth=yes&ghexport-repo-url=https://github.com/carstingaxion/gatherpress-demo-data&ghexport-pr-action=create&ghexport-playground-root=/wordpress/wp-content/gatherpress-demo-data-main&ghexport-repo-root=/&ghexport-path=.&ghexport-content-type=custom-paths&ghexport-commit-message=Changes%20from%20Playground&ghexport-allow-include-zip=no)

https://github.com/carstingaxion/gatherpress-demo-data/assets/198883/79c19cab-24f0-47e8-9710-832aed7938ca

- [carstingaxion/gatherpress-demo-data](https://github.com/carstingaxion/gatherpress-demo-data)
   WordPress playgrounds to create & use demo-content for GatherPress

**Comment by carstingaxion** [comment]
If you like it :+1: , you can **create a new repository** from my new [template repository](https://github.com/carstingaxion/crud-the-docs-playground) for your own tests, in isolation from GatherPress.

https://github.com/carstingaxion/crud-the-docs-playground

**Comment by carstingaxion** [comment]
Note to self: 

Invite members of the GatherPress slack to add their planned upcoming and their visited past WordCamps or related events to the set of demo-data via a Playground-powered-PR.

**Comment by MervinHernandez** [comment]
✅ Viewed 649 - Carsten has it

**Comment by MervinHernandez** [comment]
Hi @carstingaxion regarding this ticket - is our end goal a. to include a mention to your playground in our docs, or b. to include demo data in the plugin core and activation workflows? 
To that end, what is the PR we need to compose to achieve this tickets' goal?

**Comment by carstingaxion** [comment]
> Hi @carstingaxion regarding this ticket - is our end goal a. to include a mention to your playground in our docs, ...

No, I don't think so.
I thought that _my_ repo could be migrated into the _GatherPress_ organisation, when it is ready. 

>...or b. to include demo data in the plugin core and activation workflows? ...

Yes and No, Yes, because I would propose using the demo-data xml with the **Plugin Preview** on w.org. To make this work the [default blueprint.json](https://github.com/GatherPress/gatherpress/pull/664/files) needs to run an `importWxr` step against the file. And No, because it should not be loaded on plugin activation or anything on the user side.

Like I described in my initial comment here and in #663 , there are plenty of possibilities for a plugin like GatherPress to create different Playgrounds. A shared set of demo-data can help here, _I thought_.

>... To that end, what is the PR we need to compose to achieve this tickets' goal?

@mauteri & me talked about that recently. To achieve this goal, the [carstingaxion/gatherpress-demo-data](https://github.com/carstingaxion/gatherpress-demo-data) should be migrated to GatherPress.
