### ISSUE TITLE
Export / Import of events does not recognise date & time

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#650]
### Describe the bug

While working on #649 I realised that events exported via the default WordPress export tool are missing all date & time information. Resulting in incomplete events getting imported.

I searched for [export|import](https://github.com/search?q=export+import+repo%3AGatherPress%2Fgatherpress+language%3APHP&type=pullrequests&ref=advsearch), on the repo, with no luck.

_Is this real_, GatherPress has no mechanism in place to allow the use of the default export and import tools?

Even this is not a typical 🐛 bug, I would consider this a missing major piece.

### Steps to Reproduce

1. Make sure to have some event posts published already.
2. Go to Tools > Export
3. Select either all or event posts only
4. Download .xml file
5. Open and inspect the .xml file
6. Search for the date & time data forever ….

### Screenshots, screen recording, code snippet

Screenshots can be found attached to comments on https://github.com/carstingaxion/gatherpress-demo-data/issues/4#issuecomment-2084288400

### Environment information

[WordPress playground with GatherPress installed and some demo content.](https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/carstingaxion/gatherpress-demo-data/main/gatherpress-demo-blueprint.json)

### WordPress information

6.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
I assume, export and import have been [working correct in the past](https://github.com/GatherPress/gatherpress/pull/256). Is that correct @mauteri ?

**Comment by carstingaxion** [comment]
1. Export could maybe extended in hacky way at https://github.com/WordPress/wordpress-develop/blob/6.5/src/wp-admin/includes/export.php#L655-L677, using - [wxr_export_skip_postmeta](https://developer.wordpress.org/reference/hooks/wxr_export_skip_postmeta/) where we could echo out some pseudo-post-meta fields, before returning `false` like the default.

   What I need is a `post_meta` key, that will be reliable and 100%-sure in place for every event post. _Does such key exist?_

**Comment by carstingaxion** [comment]
2. Import will be relatively easy I think, because we can use the [`wp_import_post_data_processed`](https://github.com/WordPress/wordpress-importer/blob/71bdd41a2aa2c6a0967995ee48021037b39a1097/src/class-wp-import.php#L722) filter to unset the pseudo-post-meta and save the data into the custom DB table.

**Comment by carstingaxion** [comment]
> @carstingaxion this is a known issue and I believe was mentioned by @pbrocks in the past. It wasn't ticketed though, so thanks for adding it. 

You're welcome, thanks.

>The issue is because GatherPress uses custom tables, so that data needs to be exported/imported too and handled appropriately.

Yes, I know and already [mentioned](https://github.com/GatherPress/gatherpress/issues/650#issuecomment-2084670284) that. I didn't wanted to complain about using custom DB tables, but more that I was surprised to see, that such bare-bone defaults are missing from the current implementation.

Not being able to import existing data, means also, that nobody would be able to migrate from an existing event plugin. I surely need to take a look at what is already inside the meetup-importer, but at the moment, I think this whole import-export-thing is a major issue, to address before a 1.0 version.

**Comment by carstingaxion** [comment]
@mauteri What do you think about my sketched solution in the comments here? Did you understand, what my idea is?

**Comment by mauteri** [comment]
@carstingaxion let's review your idea in a Zoom call soon. Agreed that this should be in 1.0 release. I currently have it in Ice Box, but we'll move it up and prioritize in one of the alpha releases. Thanks!

**Comment by carstingaxion** [comment]
> > So I have to come back to my initial impulse and like to ask why the v2 is used here, while it is buggy, not well documented and not backwards compatible?
> 
> Because [v1 had even more issues](https://github.com/WordPress/wordpress-playground/issues/1183). Sadly, there doesn't seem to be a single importer that would solve all the problems. I know folks in Automattic use at least three different implementations, depending on the use-case. What we really need here is a new, reliable WXR importer that would just work, stream-handle the incoming data, correctly parse character entity references, pause, resume on failure etc. @dmsnell's work on the HTML and XML parser will come handy here.

For documentation and to not feed false expectations about the state of _the importer_, I wanted to keep this answer by @adamziel on 

https://github.com/WordPress/wordpress-playground/issues/1358

**Comment by MervinHernandez** [comment]
# RE 650 🚩 June 15 Review
✅ Read / noted that Carstin is on it

**Comment by carstingaxion** [comment]
Hey @MervinHernandez, I would appreciate if you could test the related PR. The PR is ready to be tested and can be merged afterwards.

**Comment by MervinHernandez** [comment]
@carstingaxion @mauteri commented on #655  = ✅ Test Passed

**Comment by carstingaxion** [comment]
Thanks for your intense testing @MervinHernandez !
