### ISSUE TITLE
Align with WordPress CSS Coding Standards

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#683]
### Is your enhancement related to a problem? Please describe.

Developers can already check against the [CSS Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/css/), using `npm run lint:css`, but the script fails miserably on the existing code.

Lets:

- [ ] Fix CSS issues in all code, that is not related to blocks (because this will change significantly in near future)
- [ ] Add GitHub action to run this test

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauteri** [comment]
@carstingaxion I recently did both of these while doing some updates. I didn't realize this ticket existed (or forgot it did). I'm closing this ticket, but please confirm I didn't miss anything. If I did, feel free to open this ticket again. Thanks!

**Comment by mauteri** [comment]
Recent action running Coding Standards, including CSS https://github.com/GatherPress/gatherpress/actions/runs/10271778316
