### ISSUE TITLE
Plugin should have its folder in the release's .zip file

### ISSUE THREAD

**Issue by patriciabt** [GatherPress/gatherpress#686]
### Is your enhancement related to a problem? Please describe.

Because the files in the zip are on the zip's root and not in a /gatherpress subfolder (like all the plugins usually do),, the WP installer will create the folder, based on the zip filename.

For example, if I already downloaded a gatherpress.zip in my Downloads folder (Windows), then next one will be gatherpress(1).zip, and when uploading to the site, it will be installed in gatherpress(1) subfolder where we want "gathepress"

Expected behaviour: If the zip folder contains the gatherpress subfolder and its files in that subfolder, then the plugin will be installed in that subfoler instead to creating the subfolder's name based on the zip's name, which will be discarded.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mauteri** [comment]
@patriciabt I don't think this is an issue. At least in the asset file we have in GitHub. I reproduced the same with Gutenberg here: https://github.com/WordPress/gutenberg/releases/tag/v18.5.0

Steps:

1. Downloaded `gutenberg.zip`
2. Renamed `gutenberg-foobar.zip`
3. Uploaded the `gutenberg-foobar.zip` to WordPress
4. Confirmed it directory was named `gutenberg-foobar.zip`

Let me know if this is the same thing you experience with Gutenberg plugin or if I am not following some steps correctly where you would expect something else. Attached screenshots below. Thanks!

<img width="575" alt="Screenshot 2024-06-13 at 4 15 27 AM" src="https://github.com/GatherPress/gatherpress/assets/818980/347cb83e-3334-4ce8-b363-2cae7d59abc0">

<img width="1326" alt="Screenshot 2024-06-13 at 4 15 15 AM" src="https://github.com/GatherPress/gatherpress/assets/818980/fd161694-b27f-450c-b892-a204d72c5127">

**Comment by carstingaxion** [comment]
I agree with what @mauteri wrote and suggest closing this.

I often make use of the behaviour you describe @patriciabt , which allows me to have multiple different versions of a plugin next to each other and can easily enable or disable one or the other. I do that sometimes in advance of important updates or while debugging.

**Comment by mauteri** [comment]
I'm going to close this ticket, but if you have other thoughts or concerns about this @patriciabt we can discuss and possibly reopen if there's something we are missing. Thanks!
