### ISSUE TITLE
Make RSVPs a custom comment type

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#687]
### Is your enhancement related to a problem? Please describe.

- #523 
- #665 

### Designs

- RSVP status could become a custom taxonomy registered on the comments object type. Here In pseudo-code: 
   `<?php register_taxonomy_for_object_type( 'rsvp_status', 'comment‘ ); ?> `

#### Advantages:

- allows to create variations of comment related blocks
- Does not need a user-account to RSVP
- No need for the currently used custom DB table

#### Problems:
- potential to being accessible in public via comment_feed
- https://core.trac.wordpress.org/ticket/12668
- with no reliance on a logged-in user, need to rethink https://github.com/GatherPress/gatherpress/pull/597

#### further Reading
- like a [user taxonomy](https://usersinsights.com/wordpress-user-taxonomy/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
>What about comments and users?
>
>Comments and users are object types that at this point do not support object subtypes. While there is technically a comment_type field in the comments database table, comment types are not clearly scoped in core (for example there is no register_comment_type()), so it was decided to leave them out for now.
>
>For this reason, there are no register_comment_meta() or register_user_meta() functions at this point.
>
>If you are interested in more about the history of these changes, you can read [the initial background post for these efforts](https://make.wordpress.org/core/2018/04/26/completing-the-implementation-of-metadata-registration-with-the-rest-api/), or look into the related ticket [#38323](https://core.trac.wordpress.org/ticket/38323).

https://make.wordpress.org/core/2018/07/27/registering-metadata-in-4-9-8/

**Comment by carstingaxion** [comment]
https://github.com/humanmade/roles-to-taxonomy/blob/master/inc/namespace.php

**Comment by MervinHernandez** [comment]
# RE 658 🚩 June 15 Review
✅ Read / not sure what this is about, and the merit of it. I see it's in Mike's hands, so if my assist is needed, we can get to understand this more soon.

**Comment by mauteri** [comment]
Mervin this is about how we store data. Right now we have a custom table for RSVP. This is a move to making RSVP save to comments table as a custom comment type. This allows for greater flexibility with ideas we have for non-registered user RSVP in the future, does away with a custom table, and makes exporting/importing RSVP data possible. I have made decent progress on this already.

**Comment by MervinHernandez** [comment]
✅ Reviewed June 22

Noted Mike - saw you remarked on a related ticket [692](https://github.com/GatherPress/gatherpress/pull/692)
