### ISSUE TITLE
BLOCK - Create "Add to Calendar"

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#70]
Most of the components for this are already in class-events.php, but there isn't a block to include this on the editor.

**Comment by mauteri** [comment]
@MervinHernandez I think we can close this #142 is to add the Add to Calendar feature to the Event Date block.

**Comment by mauteri** [comment]
Did this work in #142

**Comment by pbrocks** [comment]
@MervinHernandez @mauteri Let's close
