### ISSUE TITLE
Issue with the translation of the "event" part of the slug

### ISSUE THREAD

**Issue by patriciabt** [GatherPress/gatherpress#722]
### Describe the bug

I saw a strange behaviour on a German site.

When I'm logged in and my profile is in English, the event link has "event" in the slug, before the url slug
When I'm logged out, and the site is set to German, the slug becomes "veranstaltung", and on that site, it lead to a 404
This was seen on a standalone site https://tuchlaubenkonzerte.ch/ (now set to English for their visitors to be able to see the events)
On this site, it was first installed with GP 0.27.0 some months ago, and it worked, and now I updated to 0.29.3 and used the Alpha plugin "Fix GatherPress".

I first saw the same issue on our Tests/Demo site (first installed with GP 0.29.2, then upgraded to GP 0.29.3)
in the German group
 https://demo.gatherpress.org/sudsauerland/veranstaltung/ki-ai-rechtliche-aspekte-und-praktische-beispiele-beim-einsatz-in-wordpress/
But strangely, it now works, (tried as logged-out), so I'm not even sure how to reproduce

In French, it works with "évènements" in the URL, and if I manually type "events" it redirects well to "évènements" but it creates that encoded URL that is not nice to share (I should set to evenements in the translations, without accents)

Waiting for Spanish groups to test, and see how it will work with "eventos".

In my opinion, it would be better to have a setting under Permalinks (like the categories and tags) or under GatherPress settings, to be able to set a user-defined word for that slug, and also not to have different URLs depending on the language for a given event. In the current way, the event link would be different if the site admin changes the language. And we should even allow to not have anything between the domain name and the event slug in the permalinks

### Steps to Reproduce

Not sure

### WordPress information

Version 6.5.5
Permalink structure  /%postname%/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patriciabt** [comment]
For now, I solved it temporarily on my friend's site by changing in the gatherpress-de_DE.po and .mo to:

#: includes/core/classes/class-event-setup.php:141
msgctxt "Post Type Slug"
msgid "event"
msgstr "event"

---
instead of "veranstaltung"

maybe good to have some input from @carstingaxion (when you are back from holidays :D )

**Comment by patriciabt** [comment]
For the change request and to have it in options, I was thinking something like in this example (bbPress), because for events, someone might well want to call them concerts, meetings, masses, whatever...

![image](https://github.com/GatherPress/gatherpress/assets/1843660/e6b007fb-e2ee-4251-b445-637621891543)

**Comment by mauteri** [comment]
@patriciabt cool, let's chat about this in Friday's huddle and put an action item together. Just to check, did you try re-saving permalinks on the site? That can cause unexpected issues if the permalinks haven't been updated and usually best first step with issues like this. Thx!

**Comment by carstingaxion** [comment]
> @mauteri: *@patriciabt cool, let's chat about this in Friday's huddle and put an action item together. Just to check, did you try re-saving permalinks on the site? That can cause unexpected issues if the permalinks haven't been updated and usually best first step with issues like this. Thx!*

This is related (https://github.com/GatherPress/gatherpress/issues/628#issuecomment-2171891232) to the missing `has_archive` property of the post type registration. @mauteri might have missed this relation in the first PR, when the translated slugs where introduced in #563 and #565.

Let's see if I can fix this.

**Comment by carstingaxion** [comment]
- when site default is set to EN, and I as a user select _German_ in my profile, I don't get any translations (because the translation files are not part of the plugin anymore and haven't been downloaded to the server yet) **(this needs to be fixed in GatherPress)**
- when site default is set to DE and all language updates are installed, I can switch back to make the site default EN. Now I do get german translations, when set in my user profile. (But I'll not get any updates on that translations, until a site-admin will do the former steps again!) **(This needs a workaround, too)**

> re-saving permalinks

... won't be enough, because GatherPress might have to change the logic here. Instead of using the users language, the language of the event slug should be dictated by the sites default language!

For all things going further, a site owner might have to use a dedicated multilingual plugin.

**Comment by patriciabt** [comment]
same issue on our demo site now
https://demo.gatherpress.org/sudsauerland/veranstaltung/performance-simon-kraft-wordpress-meetup-suedsauerland-10/ doesn't work
if replacing by event, it works
https://demo.gatherpress.org/sudsauerland/event/performance-simon-kraft-wordpress-meetup-suedsauerland-10/

**Comment by mauteri** [comment]
Should we flush rewrite rules when site language is changed?

**Comment by patriciabt** [comment]
resaving the permalinks doesn't solve this.

Also, in my opinion it's not a good idea to have a slug in the translation strings, because 1. if the site changes, the url to event changes which is not a good idea and 2. people might want to give another name than "event", see my last paragraph above in the first text in this issue and the bbPress example. I don't think "the language of the event slug should be dictated by the sites default language" as you say @carstingaxion I think the slug should be defined by the organizers

**Comment by mauteri** [comment]
Ok, got it. So maybe this is a setting in GatherPress then. We should do the same for venue, topics, etc as well.

**Comment by patriciabt** [comment]
hmmm I feel the "decisions, not options" is in the way here :D 
maybe to be discussed during next Friday's huddle

**Comment by patriciabt** [comment]
why is it now saved with the index.php part of the slug???
https://demo.gatherpress.org/suedsauerland/index.php/veranstaltung/performance-simon-kraft-wordpress-meetup-suedsauerland-10/

**Comment by carstingaxion** [comment]
> Hello Team! I've been playing around with the demo site creating some contents and IMHO it is a very nice project! 👍

Hello and thank you for your kind words @enrico-sorcinelli !

> Me too I just ran into this issue. IMHO I think that using translations for slugs settings (or generically settings used programmatically and not only as simple strings on FE side) it isn't a too safe idea.

You are right and we agree. We came to that conclusion also and are looking forward to fix this.

> I mean that even if there is a context, translators might also use characters (like spaces. newlines, UTF8 characters and so on) that can break something or cause unexpected behaviors without a suitable validation.

Another valid reason to not do it, like it is. 
Thanks for that, too.

**Comment by carstingaxion** [comment]
@patriciabt , @enrico-sorcinelli , @hagege

We have a fix for the rewrite base issue, we all encountered.

Please have a look at the the Playground Preview link of PR #812 to test this instantly.

**Comment by mauteri** [comment]
Thanks @leobard would you mind putting in a new issue for this? What you experienced sounds like a bug and rewrite rules should be flushed if those get changed.
