### ISSUE TITLE
Datetime formatting confussion

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#727]
### Describe your question

I'm still unsure if the behaviour of localised date and times is working how it is supposed to work.

1. This is my (logged-in) view of the homepage, https://gatherpress.org/
   ![grafik](https://github.com/user-attachments/assets/1eac088d-3ae6-4696-9898-cff85cd6beb4)

2. This is my (logged-in) view of an event, https://gatherpress.org/event/gatherpress-weekly-huddle-49/
   ![grafik](https://github.com/user-attachments/assets/ac700d83-8ab5-471f-8b60-1c6f79932b35)

3. And this is my selected timezone and formatting settings in my user profile https://gatherpress.org/wp-admin/profile.php
   ![grafik](https://github.com/user-attachments/assets/27bd6ca4-28e1-49cc-8f66-8d0ef9a22f70)

_**Is the different time-formatting wanted?**_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patriciabt** [comment]
Oh right!
On the event posts it takes the format we define correctly
but in the query added on the home page (with the Event list block) it takes the format we have to define in the block
![image](https://github.com/user-attachments/assets/ace41f5c-e6bb-4201-8630-51bae34515e7)

I tried to empty that format on the right (in the block) but it still shows that format, which is the site default: D, M j, Y, g:i a T

Not sure how to solve that

**Comment by carstingaxion** [comment]
Thank you for clarification @patriciabt ! 

For the current/old Event list block, I would suggest the ***won't fix*** label and keep as is.

In the future, I hope for version 0.30.0, all of the use-cases here should be handled by an updated version of the Event date block. So that should be fine, but needs documentation. Something like:

>The *Event date* block shows the date & time of the current event. Its formatting can change depending on editors choice and the currently logged-in user. 
>
>By default the block uses the site-wide default from the GatherPress settings. An editor can overwrite this formatting on the block level. A logged-in user would get the block rendered with their custom date & time formatting, if set in her user profile,
