### ISSUE TITLE
Checkbox to toggle latitude and longitude in Venue block

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#736]
In version 0.30.0 we released a feature that automatically includes latitude and longitude values to our venue map. In this version, I'd like to include a checkbox that states something like "Generate map coordinates". If unchecked, a field to manually include latitude and longitude appear (prefilled if the coordinates were already generated). 

This allows people to refine coordinates if they are off or include coordinates if the service goes down for any given reason.

**Comment by stephenerdelyi** [comment]
PR opened: https://github.com/GatherPress/gatherpress/pull/877

**Comment by MervinHernandez** [comment]
QUEUED for discussion on October 25
- Jeff has latest work on this to update everyone about

**Comment by MervinHernandez** [comment]
In progress by Jeff + Steve

**Comment by MervinHernandez** [comment]
Discussed -- very close to completion.

**Comment by MervinHernandez** [comment]
Near completion -- will share checkpoint tomorrow during call.
