### ISSUE TITLE
TEMPLATE Default Event Template

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#76]
On new event in editor, setup a default template with common event blocks in displayed ready for configuration.

**Comment by MervinHernandez** [comment]
I created a custom FSE template for `events` which is alive on both wpNashville and in gatherpress site.
Can you leverage this by baking it into the plugin, and if the person installing gatherpresess uses `twenty-twenty-two` then it will be auto poulated.



![Image](https://user-images.githubusercontent.com/8400371/188206342-b10109a0-6e01-439b-b05c-c0ccc508cac3.png)

**Comment by mauteri** [comment]
@MervinHernandez will need to keep it to just GatherPress blocks as we can't assume any other blocks will be registered.

**Comment by MervinHernandez** [comment]
That sounds fine - my thought is just to bake in a template for default rendering of a single-event.

**Comment by MervinHernandez** [comment]
ACTIVE CONVERSATION = this should be aligned between admin side (writing experience and view) and front-end rendering. Paul has thoughts on this.

**Comment by mauteri** [comment]
MVP of this is completed. We can revisit block layout in the future, but wanted to have our basic blocks populating in a new event.

**Comment by pbrocks** [comment]
@MervinHernandez @mauteri Let's close
