### ISSUE TITLE
CREATE Block - Event Date

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#77]
A block that will display the event start/end date and time. Can be basic for now, but should eventually have configuration options for display.

**Comment by bluecollarcoders** [comment]
I'll take this ticket

**Comment by MervinHernandez** [comment]
Is this still open? And how is this different from the `post date` block?

**Comment by mauteri** [comment]
Event date is based on start/end times (different than post date, which is a publish date). It's unique to the event post type.

**Comment by pbrocks** [comment]
https://github.com/GatherPress/gatherpress/pull/146

**Comment by pbrocks** [comment]
@MervinHernandez @mauteri Let's close
