### ISSUE TITLE
Save event start and end datetimes and timezone as meta

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#803]
### Is your enhancement related to a problem? Please describe.

Currently, GatherPress stores datetimes and timezone to a custom table which is used to query events in a scalable way. This change is to ALSO store this data as post meta so it is more easily accessible to developers and in the API. We can use the same approach of pseudo post meta illustrated in this ticket https://github.com/GatherPress/gatherpress/issues/560

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
This sounds interesting, but I wonder if you really want to STORE the data in a second place or just make it available through the common APIs, post_meta for example?

**Comment by mauteri** [comment]
@carstingaxion yeah, i was thinking that. the approach you illustrated in #560 for getting data from other places via post meta filter could suffice here.

**Comment by carstingaxion** [comment]
I agree. One thing to keep in mind is, in opposite to #560, we need to make sure that meta revisions are disabled for that. Otherwise we could ran into out-of-sync issues with the custom db table.

https://make.wordpress.org/core/2023/10/24/framework-for-storing-revisions-of-post-meta-in-6-4/

**Comment by mauteri** [comment]
> I agree. One thing to keep in mind is, in opposite to #560, we need to make sure that meta revisions are disabled for that. Otherwise we could ran into out-of-sync issues with the custom db table.
> 
> https://make.wordpress.org/core/2023/10/24/framework-for-storing-revisions-of-post-meta-in-6-4/

Good call!
