### ISSUE TITLE
seeing The GatherPress Alpha plugin notice

### ISSUE THREAD

**Issue by shawfactor** [GatherPress/gatherpress#807]
### Describe the bug

I am getting a notice in wp-admin  and wp-admin/network saying:

The GatherPress Alpha plugin is not installed or activated. This plugin is currently in heavy development and requires GatherPress Alpha to handle breaking changes. Please [download and install GatherPress Alpha](https://github.com/GatherPress/gatherpress-alpha) to ensure compatibility and avoid issues.

But as per the screenshot below both are activated (network activated infact). Maybe this is because I am using multisite. If so this needs to be corrected

![Screenshot from 2024-08-16 19-39-12](https://github.com/user-attachments/assets/9c112ca8-0def-4d61-b708-432f35ae145c)

### Steps to Reproduce

Network activate both GatherPress and GatherPress Alpha Version 0.30.0 on  multisite

### Screenshots, screen recording, code snippet

![Screenshot from 2024-08-16 19-39-12](https://github.com/user-attachments/assets/497d349d-2d95-4666-b994-3f27ca287d59)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
Hello Pete,

thanks for your fast feedback!

I guess … I messed this up recently with #785 and will fix it. 
Thanks!
