### ISSUE TITLE
CREATE Non-User RSVP Workflow

### ISSUE THREAD

**Issue by MervinHernandez** [GatherPress/gatherpress#83]
This feature allows users without an account to RSVP to an event. Basic info (First name, Last name, Email, possibly other fields that can be added) will trigger and email send with a link to the address to confirm. Infrastructure can include a queuing system that deletes non-confirmations every 24-48 hours. More thought/discussion should be given to this feature to flesh it out a bit more.

Also see `CampTix` 
Also see #86

**Comment by MervinHernandez** [comment]
I'd like this to be picked up -- as is a feature that would make the plugin HIGHLY VALUABLE to other local community organizers.

**Comment by mauteri** [comment]
So with First name, Last name, and Email this is basically all the information you need to CREATE a user. I'm thinking once it's confirmed, this could be a type of registration. Maybe after the queuing it creates a Subscriber role or just a non-member custom role where a user's password isn't set (just generates one). Once a user adds/changes their password the role changes to Subscriber. In the queuing system we can add a Cron Job to remove non-confirmations after 24-48 hours.

**Comment by MervinHernandez** [comment]
Agreed - minimum required fields for creating a WP user, would be ideal baseline functionality to include with the GP plugin. 
✅ ENABLED core WP "Anyone can register" -> BP took over the contents of the `/register` page.

**Comment by MervinHernandez** [comment]
# UPDATE Button Actions
See open `@todo` regarding button actions https://github.com/GatherPress/gatherpress/blob/2f6b16f9d9030c6f1072ee8f84ebf6b2d342f6b0/src/components/AttendanceSelector.js#L152 
- [ ] CRAETE Conditional for whether user is logged in
- [ ] IF Logged in = then follow RSVP workflow
- [ ] IF not logged in = redirect user to `/register`

**Comment by MervinHernandez** [comment]
@mauteri I can't go live with funneling people to RSVP via our site (WP Nashville) without having a workflow to capture them as a new site user (registration).

Granted, I can create this workflow using Gravity forms - I think we should consider a baked in method to get user registrations, via Vanilla WP.

**Comment by mauteri** [comment]
@MervinHernandez you don't appear to have the ability to register to the site turned on. I would start there.

https://wpnashville.com/wp-login.php?redirect_to=https%3A%2F%2Fwpnashville.com%2F

**Comment by MervinHernandez** [comment]
Discussed - Mervin-Mike - August 4
* Mike will make something happen for non-logged-in users, to follow default wp registration workflow
* This will follow the meetup workflow, most closely

---

# Desired Workflow
* Default wp registration form, with available option for "login" for folks who are are already a member
* If not-logged-in = open modal > "login or register" link
* If logged in = record RSVP

**Comment by MervinHernandez** [comment]
@mauteri - acknowledging this is in `Done` status -- Mervin is excited and installing in WP Nash now!
