### ISSUE TITLE
Replace "Open Street Maps" with "OpenStreetMap"

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#833]
### Is your enhancement related to a problem? Please describe.

by the suggestion of @cyrfercom in the german language pack, I wanted to make sure, looked up https://www.openstreetmap.org/ and can confirm: GatherPress needs to fix this, not the polyglots.

![image](https://github.com/user-attachments/assets/7c640698-8a78-44f4-81e2-07fdf7b0058c)

- [ ] https://github.com/GatherPress/gatherpress/blob/5619fbf869be9f103137885636695ea65665de13/docs/user/2-gatherpress-settings.md#L24
- [ ] https://github.com/GatherPress/gatherpress/blob/5619fbf869be9f103137885636695ea65665de13/includes/core/classes/settings/class-general.php#L117

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matt-galdino** [comment]
Hi. I'll be working on this issue.
