### ISSUE TITLE
Move validate methods to new class-validate.php

### ISSUE THREAD

**Issue by mauteri** [GatherPress/gatherpress#865]
Currently there are a bunch validate methods in `class-event-rest-api.php` that I'd like to move to a general validate class.

We can remove the `validate_` prefix from these methods when we move them. Make them static methods, eg, `validate_event_post_id` method will be `Validate::event_post_id`.

Unit tests will need to be moved as well.

**Comment by JordanPak** [comment]
I'ma take a shot at this one :)
