### ISSUE TITLE
Venue info aren't shown in the editor screen if `Settings` panel is initially closed

### ISSUE THREAD

**Issue by enrico-sorcinelli** [GatherPress/gatherpress#867]
### Describe the bug

When editing an `Event`, venue info and map in the editor screen are shown only if `Settings` panel is initially open.
Only by opening the `Settings` panel again, the venue info will be rendered.

Even it's not a strictly functional bug (it's an admin UI thing) it can be a little bit misleading.

### Steps to Reproduce

1. Create new `Event` and assign it a venue (or open an existing `Event` with a venue).
2. Close `Settings` panel if it's opened. 
3. Close current event post and re-open it.
4. In the editor screen see "The No venue selected." next to the location icon.

By opening the `Settings` panel again, the venue info will be rendered.

### Environment information

- PC/Ubuntu Linux
- Google Chrome 128.0.6613.137

### WordPress information

https://demo.gatherpress.org/ instance

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by carstingaxion** [comment]
Hello @enrico-sorcinelli ,

thank you for taking the time and reporting.
Yes, I can confirm this bug, I mentioned this too.

One of the actual screenshots shows this too, as the *WordCamp Granada* has for sure a venue set, as one can see [in the demo-data](https://github.com/GatherPress/gatherpress-demo-data/blob/64775dc4cc6fadfd23cd92d339f18a05fb33bd7b/GatherPress-demo-data-2024.xml#L877) source repo.

![screenshot of event, that has a venue set, but it is isn’t shown](https://github.com/GatherPress/gatherpress/raw/main/.wordpress-org/screenshot-2.png)

**Comment by mauteri** [comment]
Merged https://github.com/GatherPress/gatherpress/pull/935 and confirm that this is fixed. Thx!
