### ISSUE TITLE
Do not link attendees to author archives 

### ISSUE THREAD

**Issue by carstingaxion** [GatherPress/gatherpress#934]
### Is your enhancement related to a problem? Please describe.

Currently the RSVP Response block shows a list of all users, each linked to their respective author archive.

Given that I need to register on a page to be able to RSVP, it’ll be more often than not, that users are just subscribers, that never write a post at all. Linking to their most likely empty author archives makes not a lot of sense (for me). 

![IMG_0231](https://github.com/user-attachments/assets/7562b2e1-2617-46d0-beb4-5b60e9924eae)

### Designs

Instead I’d like to see this attendee URL being populated by the user_website meta, if set.
If not set, don’t show any link at all.

One exception could be made, for real authors, etc.

While it might be wrong to search (aka query) for posts published by the current user, GatherPress could check for the capabilities of the user in question. If user_can edit_posts, the link the author archive could be used in preference over the user_meta URL.
But even that could and should be discussed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mauteri** [comment]
New version of the RSVP Response block will allow toggling link to profile with the use of Comment Author Name block and Avatar block. PR where this is being actively worked on: https://github.com/GatherPress/gatherpress/pull/959

**Comment by mauteri** [comment]
Fixed here https://github.com/GatherPress/gatherpress/pull/959
